### ISSUE TITLE
Outdated?

### ISSUE THREAD

**Issue by TheFishlad** [nizewn/Dodong#41]
Hiya, I'm still new to this whole thing. But running my code right from replit gives me this error, I updated through the shell, put in my token, and had touched nothing else. Whats the deal with this?
![image](https://user-images.githubusercontent.com/115974984/196113032-609e43c8-ac9b-4bd8-a82b-cc609f973e15.png)

**Comment by nizewn** [comment]
You probably have node-fetch v3 which doesn't support cjs, use v2 instead
```sh
npm uninstall node-fetch
```
```sh
npm install node-fetch@2
```

**Comment by TheFishlad** [comment]
Alrighty thank you, I'll give it a go in a few hours. 3 am moment

**Comment by TheFishlad** [comment]
![image](https://user-images.githubusercontent.com/115974984/196332441-cb93ff60-88b0-4805-88d0-35fcaedc450a.png)

Getting this one now... Apologies for being rather dumb on this stuff.

**Comment by TheFishlad** [comment]
Nevermind, I figured it out through the developer portal. Thank you!
